name: Testing with Pytest
run-name: Pytest

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Run pytest (with coverage + JUnit)
        run: |
          pytest --maxfail=1 --disable-warnings \
                 --cov=src --cov-report=term-missing \
                 --junitxml=pytest-report.xml
        env:
          PYTHONPATH: .

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-report.xml
