name: Python Unittests
run-name: Unittest

on:
  push:
    branches:
      - main
      - 'releases/**'
    branches-ignore:
      - dev
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"
  label:
    types: [created]
  issues:
    types: [opened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unittest (scoped)
        run: python -m unittest discover -s test -p "test_unittest.py" -v
        env:
          PYTHONPATH: .
