name: Python Unittests
run-name: Unittest

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "requirements.txt"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unittests (scoped)
        run: python -m unittest discover -s test -p "test_unittest.py" -v
        env:
          PYTHONPATH: .

      - name: Notify on success
        if: success()
        run: echo "Unit tests passed successfully ✅"

      - name: Notify on failure
        if: failure()
        run: echo "Unit tests failed ❌"
